.github/workflows/commits.yaml
Run CI on push too so main gets coverage reports.
=> run on push too

.github/workflows/commit.yaml
Avoids creating duplicate CI jobs on PRs by filtering "push" workflow executions by branch.
=> avoid duplicate jobs on prs

packages/iocraft-macros/src/lib.rs, packages/iocraft-macros/tests/component.rs, packages/iocraft-macros/tests/element.rs
Adds support for generic type and const parameters for the component macro.
https://github.com/ccbrown/iocraft/issues/32
=> feat: support generic type parameters for component macro

packages/iocraft/Cargo.toml
I was trying to print out a table but my program would panic with the error `called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity`. This was due to that if `taffy` does not have its `alloc` or `std` features enabled then it uses arrays with a maximum capacity, which limits e.g. in my case the number of children a node can have. It didn't seem to me that the `std` feature was intentionally excluded so I added it in.
=> feat: enable "std" feature for taffy

packages/iocraft-macros/src/lib.rs, packages/iocraft-macros/tests/component.rs, packages/iocraft-macros/tests/element.rs, packages/iocraft-macros/tests/props.rs, packages/iocraft-macros/tests/with_layout_style_props.rs, packages/iocraft/src/component.rs, packages/iocraft/src/context.rs, packages/iocraft/src/element.rs, packages/iocraft/src/handler.rs, packages/iocraft/src/hook.rs, packages/iocraft/src/hooks/use_async_handler.rs, packages/iocraft/src/props.rs, packages/iocraft/src/render.rs, packages/iocraft/src/terminal.rs
This makes it possible to use iocraft futures where `Send` is required.
The downside is it requires all `Props` implementations and all context to be `Send + Sync`. In reality, what sorts of use-cases would this actually negatively impact?
Relevant: https://github.com/async-graphql/async-graphql/pull/1122
The question is probably whether this should be merged as-is or gated behind a feature flag.
- Closes #37
=> feat: make async functions send+sync

packages/iocraft/src/hooks/use_state.rs
Allows you to modify `State` by calling `.write()` to get a mutable reference. E.g. `my_map.write().insert(foo, bar)`.
- https://github.com/ccbrown/iocraft/issues/42
=> feat: add write function to State

packages/iocraft/src/element.rs
Renames the `extend` function on the internal `ExtendWithElements` trait to avoid conflicts with `std::iter::Extend`.
- https://github.com/ccbrown/iocraft/issues/42
=> fix: rename extend function to avoid std conflicts

packages/iocraft/src/canvas.rs, packages/iocraft/src/element.rs, packages/iocraft/src/handler.rs, packages/iocraft/src/hook.rs, packages/iocraft/src/hooks/use_state.rs, packages/iocraft/src/render.rs
Minor refactors to make 1.83 Clippy happy.
=> refactor: rust 1.83 clippy fixes

packages/iocraft/src/hooks/use_state.rs
- Adds `try_read` and `try_write` methods to `State`.
- Eliminates unnecessary panics for write-only operations - They're now just no-ops.
- Documents panic cases for `State`.
- https://github.com/ccbrown/iocraft/issues/48
=> feat: add try_ methods to State, document/reduce panics

packages/iocraft/Cargo.toml, packages/iocraft/src/component.rs, packages/iocraft/src/lib.rs, packages/iocraft/src/multimap.rs, packages/iocraft/src/render.rs
This improves the component recycling algorithm in cases where elements with duplicate keys are present. Now, such components will be recycled in the order they were instantiated as opposed to components being repeatedly recreated.
- https://github.com/ccbrown/iocraft/issues/48
=> fix: improve component recycling algorithm

packages/iocraft/src/component.rs, packages/iocraft/src/components/box.rs, packages/iocraft/src/render.rs
Eliminates the impact of transparent components on layout by making them "display: none".
- Fixes https://github.com/ccbrown/iocraft/issues/52
=> fix: eliminate undesired impact of transparent components on layout

README.md, examples/borders.rs, examples/calculator.rs, examples/context.rs, examples/form.rs, examples/fullscreen.rs, examples/hello_world.rs, examples/overlap.rs, examples/progress_bar.rs, examples/table.rs, examples/use_input.rs, examples/use_output.rs, examples/weather.rs, packages/iocraft-macros/src/lib.rs, packages/iocraft-macros/tests/component.rs, packages/iocraft-macros/tests/element.rs, packages/iocraft/src/components/button.rs, packages/iocraft/src/components/context_provider.rs, packages/iocraft/src/components/mod.rs, packages/iocraft/src/components/text.rs, packages/iocraft/src/components/text_input.rs, packages/iocraft/src/components/view.rs, packages/iocraft/src/element.rs, packages/iocraft/src/hooks/use_async_handler.rs, packages/iocraft/src/hooks/use_context.rs, packages/iocraft/src/hooks/use_output.rs, packages/iocraft/src/hooks/use_terminal_events.rs, packages/iocraft/src/lib.rs, packages/iocraft/src/render.rs
Renames `Box` to `View` to avoid conflict with `std::boxed::Box`.
- https://github.com/ccbrown/iocraft/issues/42
=> feat!: rename `Box` to `View` to avoid conflict

packages/iocraft/src/terminal.rs
Calling `crossterm::terminal::supports_keyboard_enhancement()` causes a hang when stdin isn't a terminal. This checks to see if stdin is a terminal first.
- https://github.com/ccbrown/iocraft/issues/58
=> fix: check if stdin is terminal

packages/iocraft/src/canvas.rs
If a background_color is set on the view, and it is scrolled out of view by moving the canvas up or left, overflow can happen because here we are bypassing a proper cast to an usize. This leads to addition overflow in the called method `Canvas::set_background_color` and `Canvas::clear_text`, both of which expect a usize as their inputs.
This is related to #68. I was using the second implementation in the issue, and when i added a background_color to my views, it would crash when the scrolled content is moved far enough out of the top section that the inner calculation for clearing the canvas would overflow [here](https://github.com/ccbrown/iocraft/blob/main/packages/iocraft/src/canvas.rs#L114).
=> Fix for overflow when scrolling out of bounds.

.github/workflows/commit.yaml, packages/iocraft/src/components/mixed_text.rs, packages/iocraft/src/components/mod.rs, packages/iocraft/src/components/text.rs, packages/iocraft/src/render.rs
Adds a component that can display text of mixed styles:
```rust
use iocraft::prelude::*;
fn main() {
element! {
View(
border_style: BorderStyle::Round,
border_color: Color::Blue,
width: 30,
) {
MixedText(align: TextAlign::Center, contents: vec![
MixedTextContent::new("Hello, world!").color(Color::Red).weight(Weight::Bold),
MixedTextContent::new(" Lorem ipsum odor amet, consectetuer adipiscing elit.").color(Color::Green),
])
}
}
.print();
}
```
- Closes https://github.com/ccbrown/iocraft/issues/75
=> add MixedText component

packages/iocraft/src/components/mixed_text.rs, packages/iocraft/src/components/text.rs
Ensures the underline in text like the following example isn't rendered for leading whitespace:
```rust
use iocraft::prelude::*;
fn main() {
element! {
View(
border_style: BorderStyle::Round,
border_color: Color::Blue,
width: 30,
) {
Text(align: TextAlign::Center, content: "Hello, world!", decoration: TextDecoration::Underline)
}
}
.print();
}
```
=> fix: don't underline leading whitespace for center/right aligned text

examples/calculator.rs, examples/fullscreen.rs, packages/iocraft/src/canvas.rs
Previously, we emitted an ANSI "erase in line" sequence at the end of each line. This was a problem for fullscreen apps, where the cursor position after writing out a full line was on top of the last character rather than after it. As a result, the last character was being erased. This rearranges the ANSI output for full lines to ensure that the last character is correctly written.
- https://github.com/ccbrown/iocraft/issues/83
=> fix: don't erase last col for fullscreen tuis

packages/iocraft/src/components/fragment.rs, packages/iocraft/src/components/mod.rs, packages/iocraft/src/components/text_input.rs, packages/iocraft/src/hooks/mod.rs, packages/iocraft/src/hooks/use_const.rs
- Adds the `Fragment` component, with the same functionality as in React. This is equivalent to using `ContextProvider` with no props, but is more obvious and conveys intent better.
- Adds the `UseConst` hook for storing constant values in a component.
=> feat: add fragment component and use_const hook

packages/iocraft/src/canvas.rs
Gnome is a common terminal known to fail at VS16 handling: https://ucs-detect.readthedocs.io/results.html
This adds a workaround for it so it aligns emojis correctly.
#100
=> fix: add gnome to list of bad vs16 terminals

examples/form.rs
in form example, the focused field is controlled by a `focus` State and we update it in terminal events handler, but the `KeyCode::Up` is not correctly used, which will cause wired behavior. 
simple fix by disable KeyCode::Up when the focused field is already the first one in the Form
=> fix: focus logic by arrow up in form example

examples/use_output.rs, packages/iocraft/src/hooks/use_output.rs
Follow-up to https://github.com/ccbrown/iocraft/pull/122.
Adds automatic appending of newlines when `use_stdout`'s `print` function is used without a trailing newline.
Updates the example to show how this can be leveraged.
https://github.com/ccbrown/iocraft/issues/121
=> feat: automatically append newline as needed for use_output

packages/iocraft/src/render.rs, packages/iocraft/src/terminal.rs
Resolves the issue described in https://github.com/ccbrown/iocraft/issues/118 by adopting the same behavior as Ink: If we need to erase output that was taller than the terminal, we purge the entire terminal to avoid leaving behind artifacts.
- https://github.com/ccbrown/iocraft/issues/118
=> fix: purge terminal on vertical overflow

packages/iocraft/src/render.rs, packages/iocraft/src/terminal.rs
Add `EndSynchronizedUpdate` to the list of executed commands for `impl Drop for StdTerminal`. 
In the general `terminal_render_loop`, terminal executes an enter to synchronized update, but the render may panic mid-update (for example, https://github.com/ccbrown/iocraft/issues/103), which usually causes `StdTerminal` to drop. But it never ends synchronized update which can cause issues. 
In my case, I was trying to run something akin to https://github.com/ccbrown/iocraft/pull/114 in alacritty + zellij, panic mid-update would freeze the terminal rendering (but it would accept input still); just alacritty worked as expected though (so I think it's zellij related, but I have no idea actually how). Ending synchronized update fixed the issue !
- Originally discovered while trying to panic …
=> fix: End synchronized update on StdTerminal drop
